[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
